### ISSUE TITLE
Make pieces and commands classes

### ISSUE THREAD

**Issue by BenSegal855** [ud-cis-discord/Sage#162]
Right now the entire codebase is functional code. This is good and it works but using proper classes will give us better intellisense and cleaner code. This would be a major refactor as just about ever file would need to be re-written to use classes.

**Comment by joshualyon7** [comment]
@BenSegal855 What was the structure you were imagining for this? Were you thinking that there's a `Command` class that each other class inherits from? We essentially have this functionality with the interface defined in `src/lib/types/Command.d.ts`

**Comment by BenSegal855** [comment]
> @BenSegal855 What was the structure you were imagining for this? Were you thinking that there's a `Command` class that each command inherits from? We essentially have this functionality with the interface defined in `src/lib/types/Command.d.ts`

Pretty much. Doing things this way  will let you take advantage of OOP and will let you do things like set default values. Stevebot & Klasa use this method and you can find Steve's base class [here](https://github.com/stevebot-project/steve/blob/master/src/lib/structures/commands/SteveCommand.ts) (you will probably need to look at the [klasa source code](https://github.com/dirigeants/klasa) too)

**Comment by joshualyon7** [comment]
Is making pieces classes even really necessary?
