### ISSUE TITLE
Video Tutorials for Students

### ISSUE THREAD

**Issue by j-keffer** [ud-cis-discord/Sage#220]
It'd be nice to have some shorts demonstrating how to use e.g. `s;private`, `s;anonymous`, etc.

I did this in lecture this semester (The video is on Canvas, let me know if you want access) and it seems to have increased their usage.  Having something we could point students in any course to at the beginning of the semester would be great.

**Comment by joshualyon7** [comment]
[one such video](https://github.com/ud-cis-discord/ud-cis-discord.github.io/commit/b6c16b0fe93adbee03463dd205dfa916e78a2401)

**Comment by joshualyon7** [comment]
Sorry for getting to this so incredibly late, I would love that canvas video if you get the chance @j-keffer
